# Generated by Django 5.2.1 on 2025-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'continents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'currencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'timezones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('official_name', models.CharField(blank=True, max_length=150, null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=10, null=True)),
                ('subregion', models.CharField(blank=True, max_length=10, null=True)),
                ('un_member', models.BooleanField(default=True)),
                ('independent', models.BooleanField(default=True)),
                ('cca2', models.CharField(blank=True, max_length=2, null=True)),
                ('cca3', models.CharField(blank=True, max_length=3, null=True)),
                ('start_of_week', models.CharField(blank=True, max_length=10, null=True)),
                ('flag_url', models.URLField(blank=True, null=True)),
                ('coat_of_arms_url', models.URLField(blank=True, null=True)),
                ('borders', models.ManyToManyField(related_name='bordering_countries', to='countries.country')),
                ('continents', models.ManyToManyField(related_name='countries', to='countries.continent')),
                ('currencies', models.ManyToManyField(related_name='countries', to='countries.currency')),
                ('languages', models.ManyToManyField(related_name='countries', to='countries.language')),
                ('timezones', models.ManyToManyField(related_name='countries', to='countries.timezone')),
            ],
            options={
                'db_table': 'countries',
                'ordering': ['common_name'],
            },
        ),
    ]
