# Generated by Django 5.2.1 on 2025-05-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='borders',
            field=models.ManyToManyField(blank=True, null=True, related_name='bordering_countries', to='countries.country'),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('code', 'name')},
        ),
    ]
