# Generated by Django 5.2.1 on 2025-05-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_alter_currency_unique_together_alter_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('code', 'name')},
        ),
    ]
