# Generated by Django 5.2.1 on 2025-05-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_alter_currency_code_alter_currency_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('code', 'name', 'symbol')},
        ),
    ]
