# Generated by Django 5.2.1 on 2025-05-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0007_alter_currency_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='subregion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
