# Generated by Django 5.2.1 on 2025-05-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0008_alter_country_region_alter_country_subregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='borders',
            field=models.ManyToManyField(related_name='bordering_countries', to='countries.country'),
        ),
    ]
