# Generated by Django 5.2.1 on 2025-05-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0009_alter_country_borders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='borders',
            field=models.ManyToManyField(to='countries.country'),
        ),
    ]
