# Generated by Django 5.2.1 on 2025-05-09 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0011_remove_country_capital_capital'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='capital',
            unique_together={('country', 'name')},
        ),
    ]
